import whisper
from transformers import pipeline, set_seed
"""model = whisper.load_model("base")
result = model.transcribe("audio.mp3")
print(result)
"""
summarizer = pipeline("summarization", model="google/pegasus-cnn_dailymail")
print(summarizer("""We're here at the Lee and Leibouth in Computex 2023 and we have so many LCDs, 
                RGBs, tempered glass, all of it. It looks freaking beautiful.
                 Starting with this guy right here, the 011 Vision.
                 You might be noticing, normally there's like, bars that go between your tempered glass or like along the top or something.
                 Not here, they have three tempered glass panels that all go one against each other and the one on the top's even an infinity mirror.
                 Come on, look up there. Now I know what you're thinking. Having three tempered glass panels side by side is pretty terrifying and yes, it is.
                 But fortunately, let's get in here. They do have a solution so that hopefully you don't end up with a smashed PC case before, it's even put, how do I get this off?
                 Oh, there we go. As you can see, you can take off the top and side panel. The front one, you can technically take out a bit of a pain in the arse, they don't recommend it for users.
                 This though, there is a concern that this front bit, you could smash it if you're building a case in here and stuff, so instead, they've had it just so that you can take the entire motherboard tray out.
                 This has a couple of advantages.First of all, the back of the case, you're not gonna scratch it up while you're moving it all around and building your PC.
                 And also, this right here can go in many different ways if I can figure out how to take it out. There we go.
                 So you can build your entire PC on this, but then you can also move it up into this location if you want to have a great big AIO down at the bottom for cooling, or you can move it down and have room for 240 AIO back here for just heaps and heaps of cooling.
                 For those three tempered glass panels, you might think this will be brutally expensive, but it's actually going to come in at just $139. Availability is going to be next October.
                 This October. That's fine. Moving on, here's the new O11 RGB. Now you might have noticed that in the past, this just had a single RGB strip that went down right here.
                 That's not enough RGB. Now it goes all the way around up here and across on the top and the bottom. This is achieved by using silicone for the light diffusion and there's 51 RGBs for each of these.
                 If you take a look at the back, you can see it's a little L channel. So it goes up, gets diffused, bounce out and looks beautiful.
                 That's pretty cool. I don't know if it's good as the bioluminescent one that I made, but a good job, guys. Moving on. Where's the GPU?
                 There's normally a GPU right here. It's actually, this is not a distribution plate back, but this is where the GPU is in the new O11D EVO XL.
                 This thing is pretty funny. I don't really know why you'd want to have your GPU back there, but it is a very interesting spot to put it.
                 Now this has a couple of problems, mostly how do you get your display cables in there? It's a bit of a pain in the arse. So what you have to do, we come in here, take off this. 
                 Yeah, that one there. There we go. So you have to fish your display cable in through this little grommet back here, in through the case and then drop it off down in there. It won't be too difficult. 
                 If you're using soft tubing or just an air-cooled GPU, because this whole panel right here can move out, you can plug it in and push it back in, all good. If you have a hard-line water cool one like this, it's gonna be, it won't be easy, but it's gonna look really sweet. Thanks to Secret Lab for sponsoring today's video. Secret Lab chairs are engineered to keep you incredibly comfortable for long hours at work and play.
                 Their Titan EVO 2022 chair keeps you feeling comfortable for longer with four-way lumbar support and ultra-comfortable line of different seat materials and more. All chairs come with up to a five-year extended warranty and a 49-day return policy.
                 Head to the link in the description to Checkout Secret Labs today. Maybe though, putting your GPU on the side, that is not displaying it enough. You just spend four grand or whatever on that puppy, you need to show it off. And the SUP01 does that.
                 Look at this. Right up in the front, they are just showing off your GPU for the whole world to see. Now, GPUs come in many different widths, so you can actually unscrew this and move it around so that your GPU will always be perfectly centered. 
                 This also helps to prevent graphic card sag because well, it can't sag. It's standing straight up. They do have a bracket back here to make sure that it's held in place and properly secured and putting your display cables once again, huge pain in the yard.
                 So you're gonna have to go all the way around. Let's go to the one that doesn't have a PC in it. For this play cable, you have to go in the back grommet here, down through here, up over top of your hard drives and plug it in, something like that. Once again, not very practical, but it does look friggin' sweet.
                 Let's have a look at the airflow. For the airflow on the SUP, your GPU is having air pulled in beside it and then it's coming out the back right here. Beside that is a 360 millimeter radiator for your CPU that's in taking here and you can kind of decide the balance between CPU cooling and GPU cooling based on what's in taking and what's pushing out air.
                 The real advantage of doing a computer case like this is that it allows them to have the footprint be pretty small. Like vertically, it's pretty large, but this is a 45 liter case and it's not like sticking out this way too much or this way a whole lot. Instead, it's vertically sticking out quite a bit. 
                 You do have to note though, if you have a small desk, airflow on the back is very important and you cannot just jam it up against a wall.
                 Moving on to the next generation, DK07, this has a lot of practicality upgrades. So it has the same PDLC, you see me?
                 You see me in a glass right here? It's super cool, it has a little like, you know, the LCD crystals, they do little, so you can see it or not see it, very awesome.
                 But the biggest problem with the last one was that the glass panel was just freaking huge. It was this large and that has two problems. First of all, if you wanted to just like work on your computer, like, oh, hey, I need to do something. Buh, buh, buh, buh.
                 It was a two person job to lift up that whole massive piece of glass. So this is way easier to service for one person now. Also, it helps a lot with packaging. So the last one, like when I built it, it came in this massive crate because the crate has to be well as large as the glass panel that you're putting in there.
                 So this way they can have the crate half as big and it's way more IKEA-like. Like, you can just, you know, take the box, cut it up the stairs into your apartment or whatever, it's all finding good. Before it was this massive thing that, I don't know, you need to like, forklift it into your second story window or something.
                 Huge pain in the ears. Here they also have a couple of cool features. So without having glass all the way over, they can have a little cubby rate here for all of your, I don't know, pens and what nots.
                 And then on the other side, they have a little tech cooler so that you can put your little Coca-Cola in here and have it just absolutely frigid. Also, because it is a tech, you can push the button right here and have it heat or cool. Very nice. Also back here, they have a little USB hub although the features of this desk are not nailed down yet. So put in the comments down below what you want to see. 
                 What you will be seeing though is an absolute explosion of LCD screens and computers. Take a look at this rate here. It's the UniFantil LCD. Is that right? Sweet. As you can see, there's an LCD screen rate here and the engineering required to get that to work was a huge pain in the ears. This does come with a bit of a performance drop so compared to the normal ones, these right here do about 75 CFMs. 
                 The LCD goes down to about 65, but it is crazy the stuff that they have done to get the display in here. So the bearing itself needs to be hollow so that you can put stuff through it. The shaft for the fan also has to be hollow because you know, you need to put the cables and stuff through it.
                 And the LCD screen itself is mounted onto the bearing carrier for the fan blades. Also, as you can see here, the fan blade extends up to be flush with the LCD screen so it has to be kind of cut down in. It's pretty strange, but I think that the final effect is going to be really sweet. 
                 I really want to see what you guys can pull off with a whole bunch of these. You're going to be able to connect six LCD fans to a single hub or 16 normal fans and you can kind of mix and match. So here we have 10 fans all running off of a single hub. Pretty good. 
                 Allie Lee's been doing this for a while where they have their daisy chain fans. So you know, you have your bank of fans here and it has the cable. It just comes off like that. Great, absolutely love it. The problem though is that the cable in the past could only go on one side. 
                 So I've done this personally in Tynance PC. You put all your fans on, you put it in the case, you put it up in there and you're like, ah crap, the cable's coming at the wrong side. Then you have to take all the fans off and run on a huge pain in the arms. Not a problem anymore.
                 As you can see here, now they have the male and female ends of the cable on both sides. That means that you can totally screw it up, it doesn't matter which way this goes on. You can just connect it to your fans, all good to go. Great. Oh, wow, the show floor officially closes at five and they cut the power at 505.
                 So you can't see how beautiful the RGB is on these but hopefully there's B-roll of it. We'll see how well we did. Anyway, we have three new radiators here starting off with the Gala had Trinity performance. This one here has a double fin stack. So if we look at the radiator here, did it, did it, did it. 
                 On the top, we've got the performance one and you can see that there's double the fin stack of the normal one down here. That gives you about 30 extra watts of CPU cooling which given how hungry they have been for heat dissipation is going to be very welcome, I'm sure.
                 They also have three different options for the little RGB diffuser chummy here. So we have the completely frosted one. So you have like, you know, color there, color here. Looks really sweet. 
                 They also have the double infinity mirror one where you have two different colors that are reflected a whole bunch of times and if you just need another LCD screen in your system, they've got that too. Over here the Gala had two LCD has an ASA tech pump. 
                 So these ones right here, they have their in-house design, non-performance 3200 RPM, performance 4200 RPM but if you just want that ASA tech reliability, we've got that right here. I'm not entirely sure why you need to have ASA tech taking all of your money for royalties but they do have it here. 
                 Apparently it's a trusted brand name. Just like I trust that we're gonna go home now. We're gonna get down. So if you like this video, hit like, get subscribed and just have a great old day."""))